shellEmulator: true
packages:
  - packages/*
  - examples/vue/*
  - playground
  - docs

overrides:
  chokidar: 4.0.1

catalog:
  '@nuxt/content': ^3.12.0
  '@nuxt/fonts': ^0.14.0
  '@nuxt/ui': ^4.5.1
  '@vercel/analytics': ^2.0.1
  '@vercel/speed-insights': ^2.0.0
  '@vueuse/core': ^14.2.1
  docus: ^5.8.1
  nuxt: ^4.4.2
  tailwindcss: ^4.2.2
  zod: ^4.3.6
  zod-to-json-schema: ^3.25.1

catalogs:
  build:
    '@nuxt/module-builder': ^1.0.2
    publint: ^0.3.12
    typescript: ^5.9.3
    vite-plugin-dts: ^4.5.4
  lint:
    '@antfu/eslint-config': ^7.7.3
    '@nuxt/eslint-config': ^1.15.2
    eslint: ^9.39.4
  nuxt:
    '@nuxt/devtools': ^3.1.1
  prod:
    '@nuxt/kit': 4.4.2
    defu: ^6.1.4
    pathe: ^2.0.3
    phaser: ^3.90.0
  test:
    '@nuxt/test-utils': 4.0.0
    '@vue/test-utils': ^2.4.6
    jsdom: ^29.0.1
    vitest: ^4.1.1
  types:
    '@types/node': ^24.9.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.2
  vite:
    '@vitejs/plugin-vue': ^6.0.1
    vite: ^7.1.7
  vue:
    vue: ^3.5.22

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
