name: pkg-pr-new

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  publish-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-pnpm
      - run: pnpm validate:packages
      - if: github.event_name == 'pull_request'
        run: npx pkg-pr-new publish --compact --pnpm './packages/vue' './packages/nuxt'
      - if: github.event_name == 'push'
        run: |
          npx pkg-pr-new publish --compact --pnpm --comment=off --json output.json './packages/vue' './packages/nuxt'
          cat output.json
